project:
  type: website
  render:
    - index.qmd
    - 00_introduction.qmd
    - 01_prepare_input.qmd
    - 02_APIs.qmd
    - 03_training.qmd
    - 04_architecture_comparison.qmd

website:
  title: "BPNet"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 00_introduction.qmd
        text: Introduction
      - href: 01_prepare_input.qmd
        text: Data Processing
      - href: 02_APIs.qmd
        text: APIs
      - href: 03_training.qmd
        text: Training
      - href: 04_architecture_comparison.qmd
        text: Architectures
      - href: 05_interpretability.qmd
        text: Interpretability
      - href: 06_mutagenesis.qmd
        text: Mutagenesis

format:
  html:
    html-math-method: mathjax
    theme: darkly
    toc: true
    number-sections: true
    code-tools:
      source: repo



